// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxLgsRrRcZa9qrMmTZQLRxpHo569eDF9I',
    appId: '1:652708459342:android:e97179cd477205a4f2241f',
    messagingSenderId: '652708459342',
    projectId: 'moappfinal-b334f',
    databaseURL: 'https://moappfinal-b334f-default-rtdb.firebaseio.com',
    storageBucket: 'moappfinal-b334f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnnd_lClLl4RmXqiOYDi29qVfNuLjDRGg',
    appId: '1:652708459342:ios:dbe5e72d456ce125f2241f',
    messagingSenderId: '652708459342',
    projectId: 'moappfinal-b334f',
    databaseURL: 'https://moappfinal-b334f-default-rtdb.firebaseio.com',
    storageBucket: 'moappfinal-b334f.appspot.com',
    androidClientId: '652708459342-vbm9ngk466l0vj96r15a8lvq8gdtu0rg.apps.googleusercontent.com',
    iosClientId: '652708459342-kihkja9to0ehbrmubloko1o96r8llfvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdc100Series',
  );
}
